### ISSUE TITLE
Error when importing `cv2`

### ISSUE THREAD

**Issue by pzharrington** [NERSC/nersc-ml-images#7]
https://github.com/NERSC/nersc-ml-images/blob/8b9ec14d93a23e6eb83ce148bc82c039364d6d9a/pytorch/Dockerfile#L24C1-L24C1

@sparticlesteve any reason the "headless" version is used in this install line? We get errors when trying to import `cv2`:
```
> shifter --image=nersc/pytorch:ngc-23.07-v0 python -c 'import cv2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/cv2/typing/__init__.py", line 169, in <module>
    LayerId = cv2.dnn.DictValue
AttributeError: module 'cv2.dnn' has no attribute 'DictValue'
```

**Comment by pzharrington** [comment]
Ok I see now headless is just the version without GUI stuff, that's fine. But the error is still unexplained -- I checked `/usr/local/lib/python3.10/dist-packages/cv2/dnn/__init__.pyi` in the container and indeed `cv2.dnn` is defined in that interface. So somehow import of the `dnn` stuff is failing?

@ShashankSubramanian tried `pip install --no-cache-dir --ignore-installed --user opencv-python-headless` in the container (i.e. install to PYTHONUSERBASE) and noticed it also brought in a new numpy version:
```
Collecting numpy>=1.21.2 (from opencv-python-headless)
...
Downloading numpy-1.25.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```
Not sure if/why this would have impact, the container has numpy 1.22.2 so that req should already be met...

**Comment by sparticlesteve** [comment]
did the additional install fix the issue?

I am suspicious of why pip shows both of these:
```
opencv                    4.7.0
opencv-python-headless    4.8.0.76
```

**Comment by sparticlesteve** [comment]
I guess the first one is present in the NGC base image:

```
$ shifter --image=nvcr.io/nvidia/pytorch:23.07-py3 pip list | grep opencv
opencv                    4.7.0
```

Maybe I need to remove the headless install...?

**Comment by pzharrington** [comment]
Hmm, yes I believe the additional install worked to fix the issue for @ShashankSubramanian. We probably don't need both versions in there though (not sure if the issue persists w/ the 'original' `cv2`)

**Comment by sparticlesteve** [comment]
This works for me:
```
shifter --image=nvcr.io/nvidia/pytorch:23.07-py3 python -c "import cv2"
```

I'm rebuilding the nersc pytorch image without the headless opencv install.

**Comment by sparticlesteve** [comment]
This new image appears to work, at least for this test:
```
shifter --image=nersc/pytorch:ngc-23.07-v1 python -c "import cv2"
```
